/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AtletaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Atleta;

/**
 *
 * @author SESACRE
 */
public class AtletaBuscarView extends javax.swing.JFrame {
     List<Atleta> ListaAtleta = new ArrayList<>();
    AtletaController aController = new AtletaController();
    Atleta atleta = new Atleta();
    /**
     * Creates new form AtletaBuscarView
     */
    public AtletaBuscarView() {
        initComponents();
        BuscarTotalComMedalha();
        TbListaAtleta.getColumnModel().getColumn(0).setMinWidth(200);
        TbListaAtleta.getColumnModel().getColumn(0).setMaxWidth(200);
        TbListaAtleta.getColumnModel().getColumn(1).setMinWidth(100);
        TbListaAtleta.getColumnModel().getColumn(1).setMaxWidth(100);
        podio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAtletaBuscarView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNomeAtleta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbListaAtleta = new javax.swing.JTable();
        LbInformarNomeAtleta = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblTerceiroAtleta = new javax.swing.JLabel();
        lblPrimeiroAtleta = new javax.swing.JLabel();
        lblSegundoAtleta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pódio de Atletas");

        PainelAtletaBuscarView.setBackground(new java.awt.Color(255, 255, 255));
        PainelAtletaBuscarView.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PÓDIO DE ATLETAS");
        PainelAtletaBuscarView.add(jLabel1);
        jLabel1.setBounds(33, 22, 351, 47);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PainelAtletaBuscarView.add(jLabel3);
        jLabel3.setBounds(513, 316, 0, 0);

        TxtNomeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeAtletaActionPerformed(evt);
            }
        });
        TxtNomeAtleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomeAtletaKeyReleased(evt);
            }
        });
        PainelAtletaBuscarView.add(TxtNomeAtleta);
        TxtNomeAtleta.setBounds(33, 231, 250, 24);

        TbListaAtleta.setAutoCreateRowSorter(true);
        TbListaAtleta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Gênero   ", "Ouro", "Prata", "Bronze", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbListaAtleta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TbListaAtleta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(TbListaAtleta);
        if (TbListaAtleta.getColumnModel().getColumnCount() > 0) {
            TbListaAtleta.getColumnModel().getColumn(0).setResizable(false);
            TbListaAtleta.getColumnModel().getColumn(1).setResizable(false);
            TbListaAtleta.getColumnModel().getColumn(2).setResizable(false);
            TbListaAtleta.getColumnModel().getColumn(3).setResizable(false);
            TbListaAtleta.getColumnModel().getColumn(4).setResizable(false);
            TbListaAtleta.getColumnModel().getColumn(5).setResizable(false);
        }

        PainelAtletaBuscarView.add(jScrollPane2);
        jScrollPane2.setBounds(6, 277, 501, 226);

        LbInformarNomeAtleta.setForeground(new java.awt.Color(0, 0, 0));
        LbInformarNomeAtleta.setText("Informe o nome ");
        PainelAtletaBuscarView.add(LbInformarNomeAtleta);
        LbInformarNomeAtleta.setBounds(33, 205, 92, 16);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        PainelAtletaBuscarView.add(btnAtualizar);
        btnAtualizar.setBounds(427, 227, 80, 32);

        lblTerceiroAtleta.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblTerceiroAtleta.setForeground(new java.awt.Color(0, 0, 0));
        PainelAtletaBuscarView.add(lblTerceiroAtleta);
        lblTerceiroAtleta.setBounds(70, 110, 120, 30);

        lblPrimeiroAtleta.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblPrimeiroAtleta.setForeground(new java.awt.Color(0, 0, 0));
        PainelAtletaBuscarView.add(lblPrimeiroAtleta);
        lblPrimeiroAtleta.setBounds(210, 80, 140, 30);

        lblSegundoAtleta.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblSegundoAtleta.setForeground(new java.awt.Color(0, 0, 0));
        PainelAtletaBuscarView.add(lblSegundoAtleta);
        lblSegundoAtleta.setBounds(310, 119, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/podio-atleta.png"))); // NOI18N
        PainelAtletaBuscarView.add(jLabel2);
        jLabel2.setBounds(60, 100, 350, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAtletaBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAtletaBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeAtletaActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        BuscarTotalComMedalha();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void TxtNomeAtletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeAtletaKeyReleased
        BuscarTotalComMedalhaPorNome(TxtNomeAtleta.getText());
    }//GEN-LAST:event_TxtNomeAtletaKeyReleased

    private void BuscarTotalComMedalha(){
        DefaultTableModel modeloTbAtleta = (DefaultTableModel) TbListaAtleta.getModel();
        ListaAtleta = aController.BuscarTotalComMedalha();
        modeloTbAtleta.setRowCount(0);
        for(int i = 0;i<ListaAtleta.size();i++){
           modeloTbAtleta.addRow(new Object[]{
                ListaAtleta.get(i).getNome(),
                ListaAtleta.get(i).getGenero(),
                ListaAtleta.get(i).getQTDOuro(),
                ListaAtleta.get(i).getQTDPrata(),
                ListaAtleta.get(i).getQTDBronze(),
                ListaAtleta.get(i).getQTDTotal()
           
           });
        }
    }
    
    
      private void BuscarTotalComMedalhaPorNome(String NomeAtleta){
        DefaultTableModel modeloTbAtleta = (DefaultTableModel) TbListaAtleta.getModel();
        ListaAtleta = aController.BuscarTotalComMedalhaPorNome(NomeAtleta);
        if(ListaAtleta.size()>0){
            modeloTbAtleta.setRowCount(0);
            for(int i = 0;i<ListaAtleta.size();i++){
                modeloTbAtleta.addRow(new Object[]{
                    ListaAtleta.get(i).getNome(),
                    ListaAtleta.get(i).getGenero(),
                    ListaAtleta.get(i).getQTDOuro(),
                    ListaAtleta.get(i).getQTDPrata(),
                    ListaAtleta.get(i).getQTDBronze(),
                    ListaAtleta.get(i).getQTDTotal()
                        
                });
            }
          }
      }
    
    /**
     * @param args the command line arguments
     */
      
      
      
    public void podio(){
        ListaAtleta = aController.BuscarTotalComMedalha();
        lblPrimeiroAtleta.setText(ListaAtleta.get(0).getNome());
        lblSegundoAtleta.setText(ListaAtleta.get(1).getNome());
        lblTerceiroAtleta.setText(ListaAtleta.get(2).getNome());
    
    } 
      
    public static void main(String args[]) {
                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtletaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtletaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtletaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtletaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtletaBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbInformarNomeAtleta;
    private javax.swing.JPanel PainelAtletaBuscarView;
    private javax.swing.JTable TbListaAtleta;
    private javax.swing.JTextField TxtNomeAtleta;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPrimeiroAtleta;
    private javax.swing.JLabel lblSegundoAtleta;
    private javax.swing.JLabel lblTerceiroAtleta;
    // End of variables declaration//GEN-END:variables
}
