/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.AtletaController;
import controller.MedalhaController;
import controller.ModalidadeController;
import controller.PaisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Atleta;
import model.Medalha;
import model.Modalidade;
import model.Pais;


/**
 *
 * @author Mateus
 */
public class AtletaView extends javax.swing.JFrame {
    List<Atleta> ListaAtleta = new ArrayList<>();
    AtletaController aController = new AtletaController();
    Atleta atleta = new Atleta();
    /** Creates new form atletaView */
    public AtletaView() {
        initComponents();
        carregarAtleta();
        txtCodAtletas.setEnabled(false);
        txtNomeAtleta.setEnabled(false);
        LotarComboboxPais();
        LotarComboboxMedalha();
        LotarComboboxModalidade();
        btnCadastrarAtletas.setEnabled(false);
        btnLimparAtletas.setEnabled(false);
        cbMedalhasAtleta.setEnabled(false);
        cbModalidadeAtleta.setEnabled(false);
        cbPaisAtleta.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGeneroAtletaGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLimparAtletas = new javax.swing.JButton();
        btnCadastrarAtletas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbModalidadeAtleta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbPaisAtleta = new javax.swing.JComboBox<>();
        cbMedalhasAtleta = new javax.swing.JComboBox<>();
        txtNomeAtleta = new javax.swing.JTextField();
        rbGeneroMascAtleta = new javax.swing.JRadioButton();
        rbGeneroFeminiAtleta = new javax.swing.JRadioButton();
        txtCodAtletas = new javax.swing.JTextField();
        btnNovoAtleta = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbBuscaAtletaS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Atletas");

        btnLimparAtletas.setText("Limpar");
        btnLimparAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparAtletasActionPerformed(evt);
            }
        });

        btnCadastrarAtletas.setText("Cadastrar");
        btnCadastrarAtletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtletasActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Medalhas");

        cbModalidadeAtleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Modalidade" }));
        cbModalidadeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModalidadeAtletaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Modalidade");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Genero");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("País");

        cbPaisAtleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Pais" }));
        cbPaisAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisAtletaActionPerformed(evt);
            }
        });

        cbMedalhasAtleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Medalha" }));
        cbMedalhasAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedalhasAtletaActionPerformed(evt);
            }
        });

        txtNomeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAtletaActionPerformed(evt);
            }
        });
        txtNomeAtleta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAtletaKeyReleased(evt);
            }
        });

        rbGeneroAtletaGroup.add(rbGeneroMascAtleta);
        rbGeneroMascAtleta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbGeneroMascAtleta.setText("Maculino");
        rbGeneroMascAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeneroMascAtletaActionPerformed(evt);
            }
        });

        rbGeneroAtletaGroup.add(rbGeneroFeminiAtleta);
        rbGeneroFeminiAtleta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rbGeneroFeminiAtleta.setText("Feminino");

        btnNovoAtleta.setText("Novo");
        btnNovoAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAtletaActionPerformed(evt);
            }
        });

        tbBuscaAtletaS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Genero", "Pais", "Esporte", "Modalidade", "Medalha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbBuscaAtletaS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbGeneroMascAtleta)
                                .addGap(18, 18, 18)
                                .addComponent(rbGeneroFeminiAtleta)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMedalhasAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(151, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbPaisAtleta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbModalidadeAtleta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNovoAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparAtletas)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrarAtletas)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbPaisAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(cbMedalhasAtleta)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModalidadeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbGeneroMascAtleta)
                    .addComponent(rbGeneroFeminiAtleta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoAtleta)
                    .addComponent(btnLimparAtletas)
                    .addComponent(btnCadastrarAtletas))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparAtletasActionPerformed
        limparCampos();
        
    }//GEN-LAST:event_btnLimparAtletasActionPerformed

    private void btnCadastrarAtletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtletasActionPerformed
       String sexo = ""; 
       
        Pais paisCB = null;
        Medalha medalhaCB = null;
        Modalidade modalidadeCB = null;
        
        paisCB = (Pais) cbPaisAtleta.getSelectedItem();
        medalhaCB = (Medalha) cbMedalhasAtleta.getSelectedItem();
        modalidadeCB = (Modalidade) cbModalidadeAtleta.getSelectedItem();
              
        atleta.setNome(txtNomeAtleta.getText());
        
        if(rbGeneroMascAtleta.isSelected()){
            sexo = "Masculino";
        }else if (rbGeneroFeminiAtleta.isSelected()){
            sexo = "Feminino";
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Sexo!");
            sexo = null;
        }
        
        atleta.setGenero(sexo);
        atleta.setPais(paisCB);
        atleta.setModalidade(modalidadeCB);
        atleta.setTipoMedalha(medalhaCB);
        
       
       
        if(txtNomeAtleta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe um Atleta","Atleta não Digitado",JOptionPane.ERROR_MESSAGE);
        
            }else{
             boolean salvar = aController.Salvar(atleta);
                if(salvar){
                    JOptionPane.showMessageDialog(this, "Atleta: "+txtNomeAtleta.getText()+
                        " salvo com sucesso! ", "Atleta Salvo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
                limparCampos();
               }else{
                JOptionPane.showMessageDialog(this, "O Atleta não pode ser salvo! ","Atleta Error",JOptionPane.ERROR_MESSAGE);
                }
        }
        carregarAtleta();
    }//GEN-LAST:event_btnCadastrarAtletasActionPerformed

    private void cbModalidadeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModalidadeAtletaActionPerformed
        if(cbModalidadeAtleta.getSelectedItem()== "Selecione uma Modalidade"){
                JOptionPane.showMessageDialog(null, "Selecione uma Modalidade Valida!","Erro na Opção",JOptionPane.ERROR_MESSAGE);
                cbModalidadeAtleta.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cbModalidadeAtletaActionPerformed

    private void txtNomeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAtletaActionPerformed

    private void rbGeneroMascAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeneroMascAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbGeneroMascAtletaActionPerformed

    private void cbPaisAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisAtletaActionPerformed
          if(cbPaisAtleta.getSelectedItem()== "Selecione um Pais"){
                JOptionPane.showMessageDialog(null, "Selecione um País Valido!","Erro na Opção",JOptionPane.ERROR_MESSAGE);
                cbPaisAtleta.setSelectedIndex(1);
        }
        
        
        
    }//GEN-LAST:event_cbPaisAtletaActionPerformed

    private void cbMedalhasAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedalhasAtletaActionPerformed
          if(cbMedalhasAtleta.getSelectedItem()== "Selecione a Medalha"){
                JOptionPane.showMessageDialog(null, "Selecione uma Medalha Valida!","Erro na Opção",JOptionPane.ERROR_MESSAGE);
                cbMedalhasAtleta.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cbMedalhasAtletaActionPerformed

    private void txtNomeAtletaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAtletaKeyReleased
          if(3 <= txtNomeAtleta.getText().length()){
            btnCadastrarAtletas.setEnabled(true);
            btnLimparAtletas.setEnabled(true);
            cbMedalhasAtleta.setEnabled(true);
            cbModalidadeAtleta.setEnabled(true);
            cbPaisAtleta.setEnabled(true);
            
        }else{
            btnCadastrarAtletas.setEnabled(false);
            btnLimparAtletas.setEnabled(false);
            cbMedalhasAtleta.setEnabled(false);
            cbModalidadeAtleta.setEnabled(false);
            cbPaisAtleta.setEnabled(false);
            rbGeneroAtletaGroup.clearSelection();
        }
    }//GEN-LAST:event_txtNomeAtletaKeyReleased

    private void btnNovoAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAtletaActionPerformed
       txtNomeAtleta.setEnabled(true);
    }//GEN-LAST:event_btnNovoAtletaActionPerformed

    
    private void LotarComboboxModalidade(){
        ModalidadeController mController = new ModalidadeController();
        mController.Buscar().forEach((p) -> {
        cbModalidadeAtleta.addItem(p);
        
        });
    
    }
    
    
    
    
    private void LotarComboboxPais(){
        PaisController pController = new PaisController();
        
        pController.Buscar().forEach((p) -> {
            cbPaisAtleta.addItem(p);
        });
    }
    
    
    private void LotarComboboxMedalha(){
        MedalhaController mController = new MedalhaController();
        
        mController.Buscar().forEach((p)->{
            cbMedalhasAtleta.addItem(p);
        });
        
        
    
    }
    
    private void carregarAtleta(){
        DefaultTableModel modeloTbAtleta = (DefaultTableModel) tbBuscaAtletaS.getModel();
        ListaAtleta = aController.Buscar();
        modeloTbAtleta.setRowCount(0);
        
        for(int i = 0; i<ListaAtleta.size(); i++){
        modeloTbAtleta.addRow(new Object[]{
            ListaAtleta.get(i).getNome(),
            ListaAtleta.get(i).getGenero(),
            ListaAtleta.get(i).getPais().getNome(),
            ListaAtleta.get(i).getModalidade().getEsporte().getNome(),
            ListaAtleta.get(i).getModalidade().getNome(),
            ListaAtleta.get(i).getTipoMedalha().getNome()
        
        });
        
        }
        
    
    }
    
         private void limparCampos(){
         txtNomeAtleta.setText("");
        btnCadastrarAtletas.setEnabled(false);
        btnLimparAtletas.setEnabled(false);
        cbMedalhasAtleta.setEnabled(false);
        cbModalidadeAtleta.setEnabled(false);
        cbPaisAtleta.setEnabled(false);
        rbGeneroAtletaGroup.clearSelection();
         }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtletaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtletaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAtletas;
    private javax.swing.JButton btnLimparAtletas;
    private javax.swing.JToggleButton btnNovoAtleta;
    private javax.swing.JComboBox<Object> cbMedalhasAtleta;
    private javax.swing.JComboBox<Object> cbModalidadeAtleta;
    private javax.swing.JComboBox<Object> cbPaisAtleta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup rbGeneroAtletaGroup;
    private javax.swing.JRadioButton rbGeneroFeminiAtleta;
    private javax.swing.JRadioButton rbGeneroMascAtleta;
    private javax.swing.JTable tbBuscaAtletaS;
    private javax.swing.JTextField txtCodAtletas;
    private javax.swing.JTextField txtNomeAtleta;
    // End of variables declaration//GEN-END:variables

}
