/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author SESACRE
 */
public class MedalhaBuscarView extends javax.swing.JFrame {

    /**
     * Creates new form MedalhaBuscarView
     */
    public MedalhaBuscarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMedalhaBuscarView = new javax.swing.JPanel();
        LbPesquisarMedalha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnListarTodasModalidades = new javax.swing.JButton();
        LbBuscarNomeMedalha = new javax.swing.JLabel();
        TxtNomeBuscarMedalhas = new javax.swing.JTextField();
        BtnBuscarMedalha = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaListaMedalha = new javax.swing.JTable();
        LbInformarNomeMedalhas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbPesquisarMedalha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LbPesquisarMedalha.setText("PESQUISAR MEDALHAS");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        BtnListarTodasModalidades.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnListarTodasModalidades.setText("LISTAR TODAS AS MEDALHAS");
        BtnListarTodasModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarTodasModalidadesActionPerformed(evt);
            }
        });

        LbBuscarNomeMedalha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LbBuscarNomeMedalha.setText("BUSCAR POR MEDALHA");

        TxtNomeBuscarMedalhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarMedalhasActionPerformed(evt);
            }
        });

        BtnBuscarMedalha.setText("OK");
        BtnBuscarMedalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMedalhaActionPerformed(evt);
            }
        });

        TabelaListaMedalha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Total"
            }
        ));
        TabelaListaMedalha.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TabelaListaMedalha.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jScrollPane2.setViewportView(TabelaListaMedalha);

        LbInformarNomeMedalhas.setText("Informe o nome ");

        javax.swing.GroupLayout PainelMedalhaBuscarViewLayout = new javax.swing.GroupLayout(PainelMedalhaBuscarView);
        PainelMedalhaBuscarView.setLayout(PainelMedalhaBuscarViewLayout);
        PainelMedalhaBuscarViewLayout.setHorizontalGroup(
            PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMedalhaBuscarViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMedalhaBuscarViewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelMedalhaBuscarViewLayout.createSequentialGroup()
                        .addComponent(LbPesquisarMedalha)
                        .addGap(108, 108, 108))))
            .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                .addGroup(PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(BtnListarTodasModalidades))
                    .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbBuscarNomeMedalha)
                            .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                                .addComponent(LbInformarNomeMedalhas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNomeBuscarMedalhas, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscarMedalha)))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelMedalhaBuscarViewLayout.setVerticalGroup(
            PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMedalhaBuscarViewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LbPesquisarMedalha)
                .addGap(18, 18, 18)
                .addComponent(BtnListarTodasModalidades)
                .addGap(32, 32, 32)
                .addComponent(LbBuscarNomeMedalha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelMedalhaBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeBuscarMedalhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarMedalha)
                    .addComponent(LbInformarNomeMedalhas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMedalhaBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMedalhaBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListarTodasModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarTodasModalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarTodasModalidadesActionPerformed

    private void TxtNomeBuscarMedalhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarMedalhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarMedalhasActionPerformed

    private void BtnBuscarMedalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMedalhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarMedalhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedalhaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedalhaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedalhaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedalhaBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedalhaBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarMedalha;
    private javax.swing.JButton BtnListarTodasModalidades;
    private javax.swing.JLabel LbBuscarNomeMedalha;
    private javax.swing.JLabel LbInformarNomeMedalhas;
    private javax.swing.JLabel LbPesquisarMedalha;
    private javax.swing.JPanel PainelMedalhaBuscarView;
    private javax.swing.JTable TabelaListaMedalha;
    private javax.swing.JTextField TxtNomeBuscarMedalhas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
