/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.EsporteController;
import controller.ModalidadeController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Esporte;
import model.Modalidade;

/**
 *
 * @author Mateus
 */
public class ModalidadeView extends javax.swing.JFrame {
    ModalidadeController mController = new ModalidadeController();
    Modalidade Modalidade = new Modalidade();
    
    /**
     * Creates new form ModalidadeView
     */
    public ModalidadeView() {
        initComponents();
        txtCodModalidades.setEnabled(false);
        txtNomeModalidade.setEnabled(false);
        btnCadastrarModalidade.setEnabled(false);
        btnLimparModalidades.setEnabled(false);
        cbEsporte.setEnabled(false);
        LotaCombobox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLimparModalidades = new javax.swing.JButton();
        btnCadastrarModalidade = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNovoModalida = new javax.swing.JToggleButton();
        txtNomeModalidade = new javax.swing.JTextField();
        txtCodModalidades = new javax.swing.JTextField();
        cbEsporte = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Modalidades");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome da Modalidade");

        btnLimparModalidades.setText("Limpar");
        btnLimparModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparModalidadesActionPerformed(evt);
            }
        });

        btnCadastrarModalidade.setText("Cadastrar");
        btnCadastrarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarModalidadeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código");

        btnNovoModalida.setText("Novo");
        btnNovoModalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoModalidaActionPerformed(evt);
            }
        });

        txtNomeModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeModalidadeActionPerformed(evt);
            }
        });
        txtNomeModalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeModalidadeKeyReleased(evt);
            }
        });

        cbEsporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Esporte" }));
        cbEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEsporteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Esportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoModalida, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimparModalidades)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCadastrarModalidade)))
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCodModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbEsporte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEsporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodModalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnNovoModalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarModalidade)
                    .addComponent(btnLimparModalidades))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparModalidadesActionPerformed
        txtNomeModalidade.setText("");
        cbEsporte.setEnabled(false);
        
    }//GEN-LAST:event_btnLimparModalidadesActionPerformed

    private void btnCadastrarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarModalidadeActionPerformed
        
        Esporte esportecb = null;        
        esportecb = (Esporte) cbEsporte.getSelectedItem();
        
        Modalidade.setNome(txtNomeModalidade.getText());
        Modalidade.setEsporte(esportecb);
        boolean salvar = mController.Salvar(Modalidade);
        
        if(txtNomeModalidade.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Informe um Nome de uma Modalidade","Modalidade não Digitada",JOptionPane.ERROR_MESSAGE);
        }else{
            if(salvar){
                JOptionPane.showMessageDialog(this, "Modalidade: "+txtNomeModalidade.getText()+
                        " salvo com sucesso! ", "Modalidade Salvo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
            
            limparCampos();
            }else{
                JOptionPane.showMessageDialog(this, "A Modalidade não pode ser salva! ","Modalidade Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnCadastrarModalidadeActionPerformed

    private void btnNovoModalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoModalidaActionPerformed
         txtNomeModalidade.setEnabled(true);
    }//GEN-LAST:event_btnNovoModalidaActionPerformed

    private void txtNomeModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeModalidadeActionPerformed

    private void txtNomeModalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeModalidadeKeyReleased

        if(3 <= txtNomeModalidade.getText().length()){
            btnCadastrarModalidade.setEnabled(true);
            btnLimparModalidades.setEnabled(true);
            cbEsporte.setEnabled(true);
        }else{
            btnCadastrarModalidade.setEnabled(false);
            btnLimparModalidades.setEnabled(false);
            cbEsporte.setEnabled(false);
        }
    }//GEN-LAST:event_txtNomeModalidadeKeyReleased

    private void cbEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEsporteActionPerformed
        if(cbEsporte.getSelectedItem()== "Selecione um Esporte"){
        JOptionPane.showMessageDialog(null, "Selecione um País Valido!");
        cbEsporte.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cbEsporteActionPerformed

    
    public void LotaCombobox(){
        EsporteController eController = new EsporteController();
        
        eController.Buscar().forEach((p) -> {
            cbEsporte.addItem(p);
        });
    
    }
    
    public void limparCampos(){
    txtNomeModalidade.setText("");
    txtNomeModalidade.requestFocus();
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalidadeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarModalidade;
    private javax.swing.JButton btnLimparModalidades;
    private javax.swing.JToggleButton btnNovoModalida;
    private javax.swing.JComboBox<Object> cbEsporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodModalidades;
    private javax.swing.JTextField txtNomeModalidade;
    // End of variables declaration//GEN-END:variables
}
