/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ModalidadeController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Modalidade;

/**
 *
 * @author SESACRE
 */
public class ModalidadeBuscarView extends javax.swing.JFrame {
    List<Modalidade> ListaModalidade = new ArrayList<>();
    ModalidadeController mController = new ModalidadeController();
    
    /**
     * Creates new form ModalidadeBuscarView
     */
    public ModalidadeBuscarView() {
        initComponents();
       CarregarEsporte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelModalidadeBuscarView = new javax.swing.JPanel();
        LbPesquisarModalidade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnAtualizarModalidades = new javax.swing.JButton();
        LbBuscarNomeModalidade = new javax.swing.JLabel();
        TxtNomeBuscarModalidade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaModalidade = new javax.swing.JTable();
        LbInformarNomeModalidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pódio de Modalidade");

        PainelModalidadeBuscarView.setBackground(new java.awt.Color(255, 255, 255));

        LbPesquisarModalidade.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        LbPesquisarModalidade.setForeground(new java.awt.Color(0, 0, 0));
        LbPesquisarModalidade.setText("PESQUISAR MODALIDADE");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        BtnAtualizarModalidades.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnAtualizarModalidades.setText("Atualizar");
        BtnAtualizarModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarModalidadesActionPerformed(evt);
            }
        });

        LbBuscarNomeModalidade.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LbBuscarNomeModalidade.setForeground(new java.awt.Color(0, 0, 0));
        LbBuscarNomeModalidade.setText("BUSCAR POR UMA MODALIDADE");

        TxtNomeBuscarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarModalidadeActionPerformed(evt);
            }
        });
        TxtNomeBuscarModalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomeBuscarModalidadeKeyReleased(evt);
            }
        });

        tbListaModalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Esporte"
            }
        ));
        tbListaModalidade.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbListaModalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tbListaModalidade);

        LbInformarNomeModalidade.setForeground(new java.awt.Color(0, 0, 0));
        LbInformarNomeModalidade.setText("Informe o nome ");

        javax.swing.GroupLayout PainelModalidadeBuscarViewLayout = new javax.swing.GroupLayout(PainelModalidadeBuscarView);
        PainelModalidadeBuscarView.setLayout(PainelModalidadeBuscarViewLayout);
        PainelModalidadeBuscarViewLayout.setHorizontalGroup(
            PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addComponent(LbPesquisarModalidade)
                        .addGap(108, 108, 108))))
            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbBuscarNomeModalidade)
                            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                                .addComponent(LbInformarNomeModalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNomeBuscarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAtualizarModalidades, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PainelModalidadeBuscarViewLayout.setVerticalGroup(
            PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LbPesquisarModalidade)
                .addGap(80, 80, 80)
                .addComponent(LbBuscarNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeBuscarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbInformarNomeModalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAtualizarModalidades)
                .addGap(163, 163, 163))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelModalidadeBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelModalidadeBuscarView, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtualizarModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarModalidadesActionPerformed
       CarregarEsporte();
    }//GEN-LAST:event_BtnAtualizarModalidadesActionPerformed

    private void TxtNomeBuscarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarModalidadeActionPerformed

    private void TxtNomeBuscarModalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeBuscarModalidadeKeyReleased
        CarregarEsportePorNome(TxtNomeBuscarModalidade.getText());
    }//GEN-LAST:event_TxtNomeBuscarModalidadeKeyReleased

    
     private void CarregarEsporte(){
        DefaultTableModel modeloTbMdalidade = (DefaultTableModel) tbListaModalidade.getModel();
        
        ListaModalidade = mController.Buscar();
        modeloTbMdalidade.setRowCount(0);
        
        for(int i = 0;i < ListaModalidade.size();i++){
            modeloTbMdalidade.addRow(new Object []{
                ListaModalidade.get(i).getID(),
                ListaModalidade.get(i).getNome(),
                ListaModalidade.get(i).getEsporte().getNome()
            });
           
        }
    
    }
    
    
    private void CarregarEsportePorNome(String NomeModalidade){
        DefaultTableModel modeloTbMdalidade = (DefaultTableModel) tbListaModalidade.getModel();
        
        ListaModalidade = mController.BuscarPorNome(NomeModalidade);
        if(ListaModalidade.size()>0){
        modeloTbMdalidade.setRowCount(0);
        
        for(int i = 0;i < ListaModalidade.size();i++){
            modeloTbMdalidade.addRow(new Object []{
                ListaModalidade.get(i).getID(),
                ListaModalidade.get(i).getNome(),
                ListaModalidade.get(i).getEsporte().getNome()
                });
           
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalidadeBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtualizarModalidades;
    private javax.swing.JLabel LbBuscarNomeModalidade;
    private javax.swing.JLabel LbInformarNomeModalidade;
    private javax.swing.JLabel LbPesquisarModalidade;
    private javax.swing.JPanel PainelModalidadeBuscarView;
    private javax.swing.JTextField TxtNomeBuscarModalidade;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbListaModalidade;
    // End of variables declaration//GEN-END:variables
}
