/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author SESACRE
 */
public class ModalidadeBuscarView extends javax.swing.JFrame {

    /**
     * Creates new form ModalidadeBuscarView
     */
    public ModalidadeBuscarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelModalidadeBuscarView = new javax.swing.JPanel();
        LbPesquisarModalidade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnListarTodasModalidades = new javax.swing.JButton();
        LbBuscarNomeModalidade = new javax.swing.JLabel();
        TxtNomeBuscarModalidade = new javax.swing.JTextField();
        BtnBuscarModalidade = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaListaModalidade = new javax.swing.JTable();
        LbInformarNomeModalidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbPesquisarModalidade.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LbPesquisarModalidade.setText("PESQUISAR MODALIDADE");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        BtnListarTodasModalidades.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnListarTodasModalidades.setText("LISTAR TODAS AS MODALIDADES");
        BtnListarTodasModalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarTodasModalidadesActionPerformed(evt);
            }
        });

        LbBuscarNomeModalidade.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LbBuscarNomeModalidade.setText("BUSCAR POR UMA MODALIDADE");

        TxtNomeBuscarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarModalidadeActionPerformed(evt);
            }
        });

        BtnBuscarModalidade.setText("OK");
        BtnBuscarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarModalidadeActionPerformed(evt);
            }
        });

        TabelaListaModalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome", "Esporte"
            }
        ));
        TabelaListaModalidade.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TabelaListaModalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jScrollPane2.setViewportView(TabelaListaModalidade);

        LbInformarNomeModalidade.setText("Informe o nome ");

        javax.swing.GroupLayout PainelModalidadeBuscarViewLayout = new javax.swing.GroupLayout(PainelModalidadeBuscarView);
        PainelModalidadeBuscarView.setLayout(PainelModalidadeBuscarViewLayout);
        PainelModalidadeBuscarViewLayout.setHorizontalGroup(
            PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(BtnListarTodasModalidades))
                    .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbBuscarNomeModalidade)
                            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                                .addComponent(LbInformarNomeModalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNomeBuscarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnBuscarModalidade)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                        .addComponent(LbPesquisarModalidade)
                        .addGap(108, 108, 108))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        PainelModalidadeBuscarViewLayout.setVerticalGroup(
            PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelModalidadeBuscarViewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(LbPesquisarModalidade)
                .addGap(18, 18, 18)
                .addComponent(BtnListarTodasModalidades)
                .addGap(32, 32, 32)
                .addComponent(LbBuscarNomeModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelModalidadeBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeBuscarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarModalidade)
                    .addComponent(LbInformarNomeModalidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelModalidadeBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelModalidadeBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListarTodasModalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarTodasModalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarTodasModalidadesActionPerformed

    private void TxtNomeBuscarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarModalidadeActionPerformed

    private void BtnBuscarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarModalidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalidadeBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModalidadeBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarModalidade;
    private javax.swing.JButton BtnListarTodasModalidades;
    private javax.swing.JLabel LbBuscarNomeModalidade;
    private javax.swing.JLabel LbInformarNomeModalidade;
    private javax.swing.JLabel LbPesquisarModalidade;
    private javax.swing.JPanel PainelModalidadeBuscarView;
    private javax.swing.JTable TabelaListaModalidade;
    private javax.swing.JTextField TxtNomeBuscarModalidade;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
