/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PaisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pais;

/**
 *
 * @author Caveirak52
 */
public class PaisBuscarView extends javax.swing.JFrame {
    List<Pais> ListaPais = new ArrayList<>();
    PaisController pController = new PaisController();
    /**
     * Creates new form PaisBuscarView
     */
    public PaisBuscarView() {
        initComponents();
        tbListaPais.getColumnModel().getColumn(0).setMinWidth(0);
        tbListaPais.getColumnModel().getColumn(0).setMaxWidth(0);
        CarregaPais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPaisBuscarView = new javax.swing.JPanel();
        LbPesquisarPais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNomeBuscarPais = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaPais = new javax.swing.JTable();
        LbInformarNomePais = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pódio de Pais");

        PainelPaisBuscarView.setBackground(new java.awt.Color(255, 255, 255));

        LbPesquisarPais.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        LbPesquisarPais.setForeground(new java.awt.Color(0, 0, 0));
        LbPesquisarPais.setText("PÓDIO DE PAÍS");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        TxtNomeBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarPaisActionPerformed(evt);
            }
        });
        TxtNomeBuscarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomeBuscarPaisKeyReleased(evt);
            }
        });

        tbListaPais.setAutoCreateRowSorter(true);
        tbListaPais.setBackground(new java.awt.Color(255, 255, 255));
        tbListaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pais", "Nome", "Ouro", "Prata", "Bronze", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListaPais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbListaPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbListaPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaPaisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbListaPais);
        if (tbListaPais.getColumnModel().getColumnCount() > 0) {
            tbListaPais.getColumnModel().getColumn(0).setResizable(false);
            tbListaPais.getColumnModel().getColumn(1).setResizable(false);
            tbListaPais.getColumnModel().getColumn(2).setResizable(false);
            tbListaPais.getColumnModel().getColumn(3).setResizable(false);
            tbListaPais.getColumnModel().getColumn(4).setResizable(false);
            tbListaPais.getColumnModel().getColumn(5).setResizable(false);
        }

        LbInformarNomePais.setForeground(new java.awt.Color(0, 0, 0));
        LbInformarNomePais.setText("Informe o nome ");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPaisBuscarViewLayout = new javax.swing.GroupLayout(PainelPaisBuscarView);
        PainelPaisBuscarView.setLayout(PainelPaisBuscarViewLayout);
        PainelPaisBuscarViewLayout.setHorizontalGroup(
            PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LbInformarNomePais)
                                    .addComponent(TxtNomeBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtualizar))
                            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                                .addComponent(LbPesquisarPais)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(141, 141, 141))
        );
        PainelPaisBuscarViewLayout.setVerticalGroup(
            PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(193, 193, 193))
            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnAtualizar))
                    .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(LbPesquisarPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbInformarNomePais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNomeBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.PREFERRED_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarPaisActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
      CarregaPais();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tbListaPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaPaisMouseClicked
        if(evt.getClickCount() == 2){
            Pais pa = new Pais();
            pa.setID((int) tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 0)); 
            pa.setNome((String) tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 1));        
            AtletasDePais ap = new AtletasDePais();
            ap.setInfo(pa);
            ap.setVisible(true);
        
        }
    }//GEN-LAST:event_tbListaPaisMouseClicked

    private void TxtNomeBuscarPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeBuscarPaisKeyReleased
        CarregaPaisPorNome(TxtNomeBuscarPais.getText());
    }//GEN-LAST:event_TxtNomeBuscarPaisKeyReleased

    private void CarregaPais(){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.BuscaTotalComMedalha();
        modeloTbPais.setRowCount(0);
        
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome(),
                ListaPais.get(i).getQTDOuro(),
                ListaPais.get(i).getQTDPrata(),
                ListaPais.get(i).getQTDBronze(),
                ListaPais.get(i).getQTDTotal()
            });
        
        }
    
    }
    
     private void CarregaPaisPorNome(String NomePais){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.BuscaTotalComMedalhaPorNome(NomePais);
        if(ListaPais.size()>0){
        modeloTbPais.setRowCount(0);
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome(),
                ListaPais.get(i).getQTDOuro(),
                ListaPais.get(i).getQTDPrata(),
                ListaPais.get(i).getQTDBronze(),
                ListaPais.get(i).getQTDTotal()
                });
            
            }
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaisBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbInformarNomePais;
    private javax.swing.JLabel LbPesquisarPais;
    private javax.swing.JPanel PainelPaisBuscarView;
    private javax.swing.JTextField TxtNomeBuscarPais;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbListaPais;
    // End of variables declaration//GEN-END:variables
}
