/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PaisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pais;

/**
 *
 * @author Caveirak52
 */
public class PaisView extends javax.swing.JFrame {
    PaisController pController = new PaisController();
    Pais pais = new Pais();
      List<Pais> ListaPais = new ArrayList<>();
    
    /**
     * Creates new form PaisView
     */
    public PaisView() {
        initComponents();
         tbListaPais.getColumnModel().getColumn(0).setMinWidth(0);
        tbListaPais.getColumnModel().getColumn(0).setMaxWidth(0);
        txtIdPais.setEnabled(false);
        txtNomePais.setEnabled(false);
        btnCadastrarPais.setEnabled(false);
        btnLimparPais.setEnabled(false);
        btnAtualizarPais.setEnabled(false);
        btnDeletarPais.setEnabled(false);
        CarregaPais();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdPais = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomePais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrarPais = new javax.swing.JButton();
        btnLimparPais = new javax.swing.JButton();
        btnNovoPais = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaPais = new javax.swing.JTable();
        btnAtualizarPais = new javax.swing.JButton();
        btnDeletarPais = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPais.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Código");

        txtIdPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPaisActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nome do País");

        txtNomePais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomePaisKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomePaisKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cadastro de País");

        btnCadastrarPais.setText("Cadastrar");
        btnCadastrarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPaisActionPerformed(evt);
            }
        });
        btnCadastrarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarPaisKeyPressed(evt);
            }
        });

        btnLimparPais.setText("Limpar");
        btnLimparPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPaisActionPerformed(evt);
            }
        });

        btnNovoPais.setText("Novo");
        btnNovoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoPaisActionPerformed(evt);
            }
        });

        tbListaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListaPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaPaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaPais);

        btnAtualizarPais.setText("Atualizar");
        btnAtualizarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarPaisActionPerformed(evt);
            }
        });

        btnDeletarPais.setText("Deletar");
        btnDeletarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaisLayout = new javax.swing.GroupLayout(jPanelPais);
        jPanelPais.setLayout(jPanelPaisLayout);
        jPanelPaisLayout.setHorizontalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelPaisLayout.createSequentialGroup()
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarPais)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarPais)
                .addGap(18, 18, 18)
                .addComponent(btnDeletarPais)
                .addGap(18, 18, 18)
                .addComponent(btnLimparPais)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        jPanelPaisLayout.setVerticalGroup(
            jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaisLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaisLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanelPaisLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPaisLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoPais)
                    .addComponent(btnCadastrarPais)
                    .addComponent(btnAtualizarPais)
                    .addComponent(btnDeletarPais)
                    .addComponent(btnLimparPais))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPaisActionPerformed
        
    }//GEN-LAST:event_txtIdPaisActionPerformed

    private void btnCadastrarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPaisActionPerformed
      
        
        if(txtNomePais.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Informe um país","País não Digitado",JOptionPane.ERROR_MESSAGE);
        }else{
              pais.setNome(txtNomePais.getText());
                boolean salvar = pController.Salvar(pais);
            if(salvar){
                JOptionPane.showMessageDialog(this, "Pais: "+txtNomePais.getText()+
                        " salvo com sucesso! ", "País Salvo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
            
            limparCampos();
            CarregaPais();
            }else{
                JOptionPane.showMessageDialog(this, "O País não pode ser salvo! ","País Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnCadastrarPaisActionPerformed

    private void btnLimparPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPaisActionPerformed
        txtNomePais.setText(" ");
        txtIdPais.setText("");
        txtNomePais.requestFocus();
         btnCadastrarPais.setEnabled(false);
            btnLimparPais.setEnabled(false);
            btnAtualizarPais.setEnabled(false);
            btnDeletarPais.setEnabled(false);
            txtNomePais.setEnabled(false);
    }//GEN-LAST:event_btnLimparPaisActionPerformed

    private void btnCadastrarPaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarPaisKeyPressed
       if(evt.getKeyCode() == evt.VK_ENTER){
         pais.setNome(txtNomePais.getText());
        boolean salvar = pController.Salvar(pais);
        
        if(txtNomePais.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Informe um país","País não Digitado",JOptionPane.ERROR_MESSAGE);
        }else{
            if(salvar){
                JOptionPane.showMessageDialog(this, "Pais: "+txtNomePais.getText()+
                        " salvo com sucesso! ", "País Salvo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
            limparCampos();
            }else{
                JOptionPane.showMessageDialog(this, "O País não pode ser salvo! ","País Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        }
    }//GEN-LAST:event_btnCadastrarPaisKeyPressed

    private void txtNomePaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePaisKeyPressed
       if(evt.getKeyCode() == evt.VK_ENTER){
         pais.setNome(txtNomePais.getText());
        boolean salvar = pController.Salvar(pais);
        
        if(txtNomePais.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Informe um país","País não Digitado",JOptionPane.ERROR_MESSAGE);
        }else{
            if(salvar){
                JOptionPane.showMessageDialog(this, "Pais: "+txtNomePais.getText()+
                        " salvo com sucesso! ", "País Salvo", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
           limparCampos();
            }else{
                JOptionPane.showMessageDialog(this, "O País não pode ser salvo! ","País Error",JOptionPane.ERROR_MESSAGE);
            }
            }
        }
    }//GEN-LAST:event_txtNomePaisKeyPressed

    private void btnNovoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoPaisActionPerformed
        txtNomePais.setEnabled(true);
    }//GEN-LAST:event_btnNovoPaisActionPerformed

    private void txtNomePaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePaisKeyReleased
        if(0<=txtNomePais.getText().length()){
            CarrgarPaisComNome(txtNomePais.getText());
        }
        
        if(3 <= txtNomePais.getText().length()){
            btnCadastrarPais.setEnabled(true);
            btnLimparPais.setEnabled(true);
            btnAtualizarPais.setEnabled(true);
            btnDeletarPais.setEnabled(true);
        }else{
            btnCadastrarPais.setEnabled(false);
              btnLimparPais.setEnabled(false);
              btnAtualizarPais.setEnabled(false);
                btnDeletarPais.setEnabled(false);
                CarregaPais();
        }
    }//GEN-LAST:event_txtNomePaisKeyReleased

    private void tbListaPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaPaisMouseClicked
         if(tbListaPais.getSelectedRow() != -1){      
             btnCadastrarPais.setEnabled(true);
            btnLimparPais.setEnabled(true);
            btnAtualizarPais.setEnabled(true);
            btnDeletarPais.setEnabled(true);
            txtNomePais.setEnabled(true);
            
            txtIdPais.setText(tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 0).toString());
            txtNomePais.setText(tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 1).toString());
         }else{
           btnCadastrarPais.setEnabled(false);
            btnLimparPais.setEnabled(false);
            btnAtualizarPais.setEnabled(false);
            btnDeletarPais.setEnabled(false);
            txtNomePais.setEnabled(false);
         
         
         }    
            
    }//GEN-LAST:event_tbListaPaisMouseClicked

    private void btnAtualizarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarPaisActionPerformed
         if(txtIdPais.getText().length()>0){
              pais.setNome(txtNomePais.getText());
              pais.setID(Integer.parseInt(txtIdPais.getText()));
                boolean Editar = pController.Editar(pais);
            if(Editar){
                JOptionPane.showMessageDialog(this, "Pais: "+txtNomePais.getText()+
                        "Editado com sucesso! ", "País Editado", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
            CarregaPais();
            limparCampos();
            }else{
                JOptionPane.showMessageDialog(this, "O País não pode ser Editado! ","País Error",JOptionPane.ERROR_MESSAGE);
            }
        
         }else{
             JOptionPane.showMessageDialog(this, "Selecione algum Pais para Editar ","Pais Error",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnAtualizarPaisActionPerformed

    private void btnDeletarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarPaisActionPerformed
         int input = JOptionPane.showConfirmDialog(null, "Você Realmente deseja Excluir esse País?","Excluir País",JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
         
        if (input == JOptionPane.YES_OPTION) {
        if(tbListaPais.getSelectedRow() != -1){
          

                 boolean excluir = pController.Excluir((int)tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 0));

             if(excluir){
                    JOptionPane.showMessageDialog(this, "País Deletado com Sucesso", "País", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/img/correct.png"));
                CarregaPais();
                limparCampos();
                }else{
                    JOptionPane.showMessageDialog(this, "O País não pode ser Deletado! ","País Error",JOptionPane.ERROR_MESSAGE);
                }


           }else{
                JOptionPane.showMessageDialog(this, "Selecione algum País para deletar ","País Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeletarPaisActionPerformed

    
    private void CarrgarPaisComNome(String NomePais){
     DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.BuscarPorNome(NomePais);
        if(ListaPais.size()>0){
        modeloTbPais.setRowCount(0);
        
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome()
                });
        
            }
        }
    }
    
    
    
    private void CarregaPais(){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.Buscar();
        modeloTbPais.setRowCount(0);
        
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome()
            });
        
        }
    
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaisView().setVisible(true);
            }
        });
    }

    public void limparCampos(){
    txtNomePais.setText("");
    txtIdPais.setText("");
    txtNomePais.requestFocus();
    
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarPais;
    private javax.swing.JButton btnCadastrarPais;
    private javax.swing.JButton btnDeletarPais;
    private javax.swing.JButton btnLimparPais;
    private javax.swing.JToggleButton btnNovoPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelPais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaPais;
    private javax.swing.JTextField txtIdPais;
    private javax.swing.JTextField txtNomePais;
    // End of variables declaration//GEN-END:variables
}
