/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PaisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pais;

/**
 *
 * @author SESACRE
 */
public class PaisBuscarView extends javax.swing.JFrame {
    List<Pais> ListaPais = new ArrayList<>();
    PaisController pController = new PaisController();
    /**
     * Creates new form PaisBuscarView
     */
    public PaisBuscarView() {
        initComponents();
        CarregaPais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPaisBuscarView = new javax.swing.JPanel();
        LbPesquisarPais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnListarTodosPaises = new javax.swing.JButton();
        LbBuscarNomePais = new javax.swing.JLabel();
        TxtNomeBuscarPais = new javax.swing.JTextField();
        BtnBuscarPais = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaPais = new javax.swing.JTable();
        LbInformarNomePais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelPaisBuscarView.setBackground(new java.awt.Color(255, 255, 255));

        LbPesquisarPais.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LbPesquisarPais.setText("PESQUISAR PAÍS");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        BtnListarTodosPaises.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        BtnListarTodosPaises.setText("LISTAR TODOS OS PAÍSES");
        BtnListarTodosPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListarTodosPaisesActionPerformed(evt);
            }
        });

        LbBuscarNomePais.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        LbBuscarNomePais.setText("BUSCAR POR UM PAÍS");

        TxtNomeBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarPaisActionPerformed(evt);
            }
        });

        BtnBuscarPais.setText("OK");
        BtnBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPaisActionPerformed(evt);
            }
        });

        tbListaPais.setBackground(new java.awt.Color(255, 255, 255));
        tbListaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListaPais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbListaPais.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jScrollPane2.setViewportView(tbListaPais);

        LbInformarNomePais.setText("Informe o nome ");

        javax.swing.GroupLayout PainelPaisBuscarViewLayout = new javax.swing.GroupLayout(PainelPaisBuscarView);
        PainelPaisBuscarView.setLayout(PainelPaisBuscarViewLayout);
        PainelPaisBuscarViewLayout.setHorizontalGroup(
            PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbBuscarNomePais)
                    .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addComponent(LbInformarNomePais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNomeBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBuscarPais)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPaisBuscarViewLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelPaisBuscarViewLayout.createSequentialGroup()
                        .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnListarTodosPaises, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(LbPesquisarPais)))
                        .addGap(170, 170, 170))))
        );
        PainelPaisBuscarViewLayout.setVerticalGroup(
            PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPaisBuscarViewLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(LbPesquisarPais)
                .addGap(18, 18, 18)
                .addComponent(BtnListarTodosPaises)
                .addGap(18, 18, 18)
                .addComponent(LbBuscarNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPaisBuscarViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomeBuscarPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarPais)
                    .addComponent(LbInformarNomePais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListarTodosPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListarTodosPaisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarTodosPaisesActionPerformed

    private void TxtNomeBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarPaisActionPerformed

    private void BtnBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBuscarPaisActionPerformed

    private void CarregaPais(){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.Buscar();
        modeloTbPais.setRowCount(0);
        
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome()
            });
        
        }
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaisBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarPais;
    private javax.swing.JButton BtnListarTodosPaises;
    private javax.swing.JLabel LbBuscarNomePais;
    private javax.swing.JLabel LbInformarNomePais;
    private javax.swing.JLabel LbPesquisarPais;
    private javax.swing.JPanel PainelPaisBuscarView;
    private javax.swing.JTextField TxtNomeBuscarPais;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbListaPais;
    // End of variables declaration//GEN-END:variables
}
