/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PaisController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Pais;

/**
 *
 * @author Caveirak52
 */
public class PaisBuscarView extends javax.swing.JFrame {
    List<Pais> ListaPais = new ArrayList<>();
    PaisController pController = new PaisController();
    /**
     * Creates new form PaisBuscarView
     */
    public PaisBuscarView() {
        initComponents();
        tbListaPais.getColumnModel().getColumn(0).setMinWidth(0);
        tbListaPais.getColumnModel().getColumn(0).setMaxWidth(0);
        Podio();
        CarregaPais();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPaisBuscarView = new javax.swing.JPanel();
        LbPesquisarPais = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNomeBuscarPais = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaPais = new javax.swing.JTable();
        LbInformarNomePais = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        lblSegundoPais = new javax.swing.JLabel();
        lblPrimeiroPais = new javax.swing.JLabel();
        lblTerceiroPais = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pódio de Pais");

        PainelPaisBuscarView.setBackground(new java.awt.Color(255, 255, 255));
        PainelPaisBuscarView.setLayout(null);

        LbPesquisarPais.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        LbPesquisarPais.setForeground(new java.awt.Color(0, 0, 0));
        LbPesquisarPais.setText("PÓDIO DE PAÍS");
        PainelPaisBuscarView.add(LbPesquisarPais);
        LbPesquisarPais.setBounds(30, 20, 268, 47);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PainelPaisBuscarView.add(jLabel3);
        jLabel3.setBounds(477, 326, 0, 0);

        TxtNomeBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeBuscarPaisActionPerformed(evt);
            }
        });
        TxtNomeBuscarPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNomeBuscarPaisKeyReleased(evt);
            }
        });
        PainelPaisBuscarView.add(TxtNomeBuscarPais);
        TxtNomeBuscarPais.setBounds(34, 267, 253, 24);

        tbListaPais.setAutoCreateRowSorter(true);
        tbListaPais.setBackground(new java.awt.Color(255, 255, 255));
        tbListaPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pais", "Nome", "Ouro", "Prata", "Bronze", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListaPais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbListaPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbListaPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaPaisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbListaPais);
        if (tbListaPais.getColumnModel().getColumnCount() > 0) {
            tbListaPais.getColumnModel().getColumn(0).setResizable(false);
            tbListaPais.getColumnModel().getColumn(1).setResizable(false);
            tbListaPais.getColumnModel().getColumn(2).setResizable(false);
            tbListaPais.getColumnModel().getColumn(3).setResizable(false);
            tbListaPais.getColumnModel().getColumn(4).setResizable(false);
            tbListaPais.getColumnModel().getColumn(5).setResizable(false);
        }

        PainelPaisBuscarView.add(jScrollPane2);
        jScrollPane2.setBounds(6, 313, 465, 160);

        LbInformarNomePais.setForeground(new java.awt.Color(0, 0, 0));
        LbInformarNomePais.setText("Informe o nome ");
        PainelPaisBuscarView.add(LbInformarNomePais);
        LbInformarNomePais.setBounds(34, 241, 92, 16);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        PainelPaisBuscarView.add(btnAtualizar);
        btnAtualizar.setBounds(391, 263, 80, 32);

        lblSegundoPais.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblSegundoPais.setForeground(new java.awt.Color(0, 0, 0));
        PainelPaisBuscarView.add(lblSegundoPais);
        lblSegundoPais.setBounds(100, 140, 110, 30);

        lblPrimeiroPais.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblPrimeiroPais.setForeground(new java.awt.Color(0, 0, 0));
        PainelPaisBuscarView.add(lblPrimeiroPais);
        lblPrimeiroPais.setBounds(220, 110, 120, 30);

        lblTerceiroPais.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        lblTerceiroPais.setForeground(new java.awt.Color(0, 0, 0));
        PainelPaisBuscarView.add(lblTerceiroPais);
        lblTerceiroPais.setBounds(320, 140, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/podio-atleta.png"))); // NOI18N
        PainelPaisBuscarView.add(jLabel1);
        jLabel1.setBounds(70, 123, 350, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPaisBuscarView, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomeBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeBuscarPaisActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
      CarregaPais();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tbListaPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaPaisMouseClicked
        if(evt.getClickCount() == 2){
            Pais pa = new Pais();
            pa.setID((int) tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 0)); 
            pa.setNome((String) tbListaPais.getValueAt(tbListaPais.getSelectedRow(), 1));        
            AtletasDePais ap = new AtletasDePais();
            ap.setInfo(pa);
            ap.setVisible(true);
        
        }
    }//GEN-LAST:event_tbListaPaisMouseClicked

    private void TxtNomeBuscarPaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeBuscarPaisKeyReleased
        CarregaPaisPorNome(TxtNomeBuscarPais.getText());
    }//GEN-LAST:event_TxtNomeBuscarPaisKeyReleased

    private void CarregaPais(){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.BuscaTotalComMedalha();
        modeloTbPais.setRowCount(0);
        
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome(),
                ListaPais.get(i).getQTDOuro(),
                ListaPais.get(i).getQTDPrata(),
                ListaPais.get(i).getQTDBronze(),
                ListaPais.get(i).getQTDTotal()
            });
        
        }
    
    }
    
     private void CarregaPaisPorNome(String NomePais){
        DefaultTableModel modeloTbPais = (DefaultTableModel) tbListaPais.getModel();
        
        ListaPais = pController.BuscaTotalComMedalhaPorNome(NomePais);
        if(ListaPais.size()>0){
        modeloTbPais.setRowCount(0);
        for(int i = 0; i < ListaPais.size();i++){
            modeloTbPais.addRow(new Object[]{
                ListaPais.get(i).getID(),
                ListaPais.get(i).getNome(),
                ListaPais.get(i).getQTDOuro(),
                ListaPais.get(i).getQTDPrata(),
                ListaPais.get(i).getQTDBronze(),
                ListaPais.get(i).getQTDTotal()
                });
            
            }
        }
    
    }
    
     
     public void Podio(){
         ListaPais = pController.BuscaTotalComMedalha();
         
         lblPrimeiroPais.setText(ListaPais.get(0).getNome());
         lblSegundoPais.setText(ListaPais.get(1).getNome());
         lblTerceiroPais.setText(ListaPais.get(2).getNome());     
     }
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaisBuscarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaisBuscarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbInformarNomePais;
    private javax.swing.JLabel LbPesquisarPais;
    private javax.swing.JPanel PainelPaisBuscarView;
    private javax.swing.JTextField TxtNomeBuscarPais;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPrimeiroPais;
    private javax.swing.JLabel lblSegundoPais;
    private javax.swing.JLabel lblTerceiroPais;
    private javax.swing.JTable tbListaPais;
    // End of variables declaration//GEN-END:variables
}
