/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;


import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Pais;
import view.AtletaBuscarView;
import view.AtletaView;
import view.EsporteBuscarView;
import view.EsporteView;
import view.MedalhaBuscarView;
import view.MedalhaView;
import view.ModalidadeBuscarView;
import view.ModalidadeView;
import view.PaisBuscarView;
import view.PaisView;
import view.PremiacaoView;

/**
 *
 * @author Caveirak52
 */
public class Olympics extends javax.swing.JFrame {
    PaisController pController = new PaisController();
    List<Pais> ListaPais = new ArrayList<>();
     
    public Olympics() {
        initComponents();
        Podio();
        
     
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BemVindo = new javax.swing.JLabel();
        lblSegundo = new javax.swing.JLabel();
        lblTerceiro = new javax.swing.JLabel();
        lblPrimeiro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnPais = new javax.swing.JMenuItem();
        btnMenuMedalhaC = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenu();
        BtnBuscarAtleta = new javax.swing.JMenuItem();
        BtnBuscarPais = new javax.swing.JMenuItem();
        BtnBuscarMedalha = new javax.swing.JMenuItem();
        BtnBuscarModalidade = new javax.swing.JMenuItem();
        BtnBuscarEsporte = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quandro de Medalhas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        BemVindo.setBackground(new java.awt.Color(0, 0, 0));
        BemVindo.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        BemVindo.setForeground(new java.awt.Color(0, 0, 0));
        BemVindo.setText("Bem Vindo ao Quadro de Medalhas");
        jPanel1.add(BemVindo);
        BemVindo.setBounds(129, 6, 605, 47);

        lblSegundo.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblSegundo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblSegundo);
        lblSegundo.setBounds(210, 240, 99, 33);

        lblTerceiro.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblTerceiro.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblTerceiro);
        lblTerceiro.setBounds(560, 250, 99, 33);

        lblPrimeiro.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        lblPrimeiro.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lblPrimeiro);
        lblPrimeiro.setBounds(390, 190, 99, 33);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/podio.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 220, 600, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Olympics-2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 60, 200, 90);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setForeground(new java.awt.Color(0, 0, 0));
        jMenu1.setText("Cadastro");

        btnPais.setText("Cadastro de País");
        btnPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaisActionPerformed(evt);
            }
        });
        jMenu1.add(btnPais);

        btnMenuMedalhaC.setText("Cadastro de Medalhas");
        btnMenuMedalhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuMedalhaCActionPerformed(evt);
            }
        });
        jMenu1.add(btnMenuMedalhaC);

        jMenuItem3.setText("Cadastro de Esporte");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cadastro de Atleta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Cadastro de Modalidade");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        Buscar.setForeground(new java.awt.Color(0, 0, 0));
        Buscar.setText("Busca");

        BtnBuscarAtleta.setText("Buscar atleta");
        BtnBuscarAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarAtletaActionPerformed(evt);
            }
        });
        Buscar.add(BtnBuscarAtleta);

        BtnBuscarPais.setText("Buscar país");
        BtnBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarPaisActionPerformed(evt);
            }
        });
        Buscar.add(BtnBuscarPais);

        BtnBuscarMedalha.setText("Buscar Medalha");
        BtnBuscarMedalha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarMedalhaActionPerformed(evt);
            }
        });
        Buscar.add(BtnBuscarMedalha);

        BtnBuscarModalidade.setText("Buscar Modalidade");
        BtnBuscarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarModalidadeActionPerformed(evt);
            }
        });
        Buscar.add(BtnBuscarModalidade);

        BtnBuscarEsporte.setText("Buscar Esporte");
        BtnBuscarEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEsporteActionPerformed(evt);
            }
        });
        Buscar.add(BtnBuscarEsporte);

        jMenuBar1.add(Buscar);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setText("Premiação");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Premiação Atleta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarPaisActionPerformed
        // TODO add your handling code here:
        PaisBuscarView PaisBuscar = new PaisBuscarView();
        PaisBuscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarPaisActionPerformed

    private void BtnBuscarAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarAtletaActionPerformed
        // TODO add your handling code here:
        AtletaBuscarView AtletaBuscar = new AtletaBuscarView();
        AtletaBuscar.setVisible(true);        
    }//GEN-LAST:event_BtnBuscarAtletaActionPerformed

    private void BtnBuscarMedalhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarMedalhaActionPerformed
       String Input = JOptionPane.showInputDialog(null,"Informe senha de Acesso","Acesso Restrito",JOptionPane.QUESTION_MESSAGE);
        if(Input != null){
        if(Input.equals("adminUninorte")){
        MedalhaBuscarView MedalhaBuscar = new MedalhaBuscarView();
        MedalhaBuscar.setVisible(true);
        }
        
        else{
        JOptionPane.showMessageDialog(null, "Senha Incorreta","Acesso Negado!",JOptionPane.ERROR_MESSAGE);
        } 
        }
    }//GEN-LAST:event_BtnBuscarMedalhaActionPerformed

    private void BtnBuscarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarModalidadeActionPerformed
        // TODO add your handling code here:
        ModalidadeBuscarView ModalidadeBuscar = new ModalidadeBuscarView();
        ModalidadeBuscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarModalidadeActionPerformed

    private void BtnBuscarEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEsporteActionPerformed
        // TODO add your handling code here:
        EsporteBuscarView EsporteBuscar = new EsporteBuscarView();
        EsporteBuscar.setVisible(true);
    }//GEN-LAST:event_BtnBuscarEsporteActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PremiacaoView pre = new PremiacaoView();
        pre.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaisActionPerformed
        PaisView paisView = new PaisView();
        paisView.setVisible(true);
    }//GEN-LAST:event_btnPaisActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       ModalidadeView modalidade = new ModalidadeView();
       modalidade.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnMenuMedalhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuMedalhaCActionPerformed
        String Input = JOptionPane.showInputDialog(null,"Informe senha de Acesso","Acesso Restrito",JOptionPane.QUESTION_MESSAGE);
        if(Input != null){
        if(Input.equals("adminUninorte")){
        MedalhaView me = new MedalhaView();
        me.setVisible(true);
        }
        
        else{
        JOptionPane.showMessageDialog(null, "Senha Incorreta","Acesso Negado!",JOptionPane.ERROR_MESSAGE);
        } 
        }
       
    }//GEN-LAST:event_btnMenuMedalhaCActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      EsporteView esporte = new EsporteView();
      esporte.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      AtletaView atleta = new AtletaView();
      atleta.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
        public void Podio(){
            
        ListaPais = pController.BuscaTotalComMedalha();
        if(ListaPais.size() >= 3){
           lblPrimeiro.setText(ListaPais.get(0).getNome());
           lblSegundo.setText(ListaPais.get(1).getNome());
           lblTerceiro.setText(ListaPais.get(2).getNome());
            }else if(ListaPais.size() == 2){
             lblPrimeiro.setText(ListaPais.get(0).getNome());
            lblSegundo.setText(ListaPais.get(1).getNome());
             lblTerceiro.setText("");
            }else if(ListaPais.size() == 1){
              lblPrimeiro.setText(ListaPais.get(0).getNome());
            lblSegundo.setText("");
             lblTerceiro.setText("");
            
            }else if(ListaPais.size() < 1){
            
            lblPrimeiro.setText("");
            lblSegundo.setText("");
             lblTerceiro.setText("");
            }
        }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olympics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindo;
    private javax.swing.JMenuItem BtnBuscarAtleta;
    private javax.swing.JMenuItem BtnBuscarEsporte;
    private javax.swing.JMenuItem BtnBuscarMedalha;
    private javax.swing.JMenuItem BtnBuscarModalidade;
    private javax.swing.JMenuItem BtnBuscarPais;
    private javax.swing.JMenu Buscar;
    private javax.swing.JMenuItem btnMenuMedalhaC;
    private javax.swing.JMenuItem btnPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPrimeiro;
    private javax.swing.JLabel lblSegundo;
    private javax.swing.JLabel lblTerceiro;
    // End of variables declaration//GEN-END:variables
}
