/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;


import view.AtletaView;
import view.EsporteView;
import view.GeneroView;
import view.MedalhaView;
import view.ModalidadeView;
import view.PaisView;

/**
 *
 * @author Caveirak52
 */
public class Olympics extends javax.swing.JFrame {
    
     
    public Olympics() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BemVindo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnModalidd = new javax.swing.JRadioButtonMenuItem();
        btnPais = new javax.swing.JMenuItem();
        BtnEsporte = new javax.swing.JRadioButtonMenuItem();
        btnGenero = new javax.swing.JRadioButtonMenuItem();
        btnAtleta = new javax.swing.JRadioButtonMenuItem();
        btnModalidade = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quandro de Medalhas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BemVindo.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        BemVindo.setText("Bem Vindo");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Olympics.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(BemVindo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(BemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        btnModalidd.setSelected(true);
        btnModalidd.setText("Cadastro Medalhas");
        btnModalidd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModaliddActionPerformed(evt);
            }
        });
        jMenu1.add(btnModalidd);

        btnPais.setText("Cadastro de País");
        btnPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaisActionPerformed(evt);
            }
        });
        jMenu1.add(btnPais);

        BtnEsporte.setSelected(true);
        BtnEsporte.setText("Cadastro de Esporte");
        BtnEsporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEsporteActionPerformed(evt);
            }
        });
        jMenu1.add(BtnEsporte);

        btnGenero.setSelected(true);
        btnGenero.setText("Cadastro Genero");
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });
        jMenu1.add(btnGenero);

        btnAtleta.setSelected(true);
        btnAtleta.setText("Cadastro Atleta");
        btnAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtletaActionPerformed(evt);
            }
        });
        jMenu1.add(btnAtleta);

        btnModalidade.setSelected(true);
        btnModalidade.setText("Cadastro Modalidade");
        btnModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalidadeActionPerformed(evt);
            }
        });
        jMenu1.add(btnModalidade);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        jMenuItem2.setText("Exemplo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaisActionPerformed
       PaisView paisView = new PaisView();
       paisView.setVisible(true);
    }//GEN-LAST:event_btnPaisActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnModaliddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModaliddActionPerformed
       MedalhaView medalhaView = new MedalhaView();
       medalhaView.setVisible(true);
    }//GEN-LAST:event_btnModaliddActionPerformed

    private void BtnEsporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEsporteActionPerformed
         EsporteView esporteView = new EsporteView ();
         esporteView.setVisible (true);
    }//GEN-LAST:event_BtnEsporteActionPerformed

    private void btnModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalidadeActionPerformed
         ModalidadeView modalidadeView = new ModalidadeView ();
         modalidadeView.setVisible (true);
    }//GEN-LAST:event_btnModalidadeActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed

        GeneroView generoView = new GeneroView ();
         generoView.setVisible (true);
    }//GEN-LAST:event_btnGeneroActionPerformed

    private void btnAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtletaActionPerformed
        AtletaView atletaView = new AtletaView ();
         atletaView.setVisible (true);
    }//GEN-LAST:event_btnAtletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Olympics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Olympics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindo;
    private javax.swing.JRadioButtonMenuItem BtnEsporte;
    private javax.swing.JRadioButtonMenuItem btnAtleta;
    private javax.swing.JRadioButtonMenuItem btnGenero;
    private javax.swing.JRadioButtonMenuItem btnModalidade;
    private javax.swing.JRadioButtonMenuItem btnModalidd;
    private javax.swing.JMenuItem btnPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
